### ISSUE TITLE
rollup production config

### ISSUE THREAD

**Issue by Rayraegah** [nerdstep/buble-riot-rollup-starter#1]
Is this a possible error?

in config/prod.js, line #9

    config.plugins[3] = replace({ 'process.env.NODE_ENV': JSON.stringify('production') })

replaces line #19 in config/dev.js

    globals()

shouldn't it be 

    config.plugins[4] = replace({ 'process.env.NODE_ENV': JSON.stringify('production') })

so it replaces line #20 in config.dev.js

    replace({ 'process.env.NODE_ENV': JSON.stringify('development') })

**Comment by nerdstep** [comment]
Good find! Just pushed the fix. Cheers.
